<?php

namespace AppBundle\Repository;

/**
 * DistrictsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des districts
     * RegionController::listeAction
     */
    public function findListeByRegion($region)
    {
        return $this->createQueryBuilder('d')
                    ->where('d.region = :region')
                    ->orderBy('d.name', 'ASC')
                    ->setParameter('region', $region)
                    ->getQuery()->getResult()
            ;
    }
}
