<?php

namespace AppBundle\Repository;

/**
 * ParoissesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParoissesRepository extends \Doctrine\ORM\EntityRepository
{
}
