<?php

namespace AppBundle\Repository;

/**
 * regionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class regionsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des regions
     */
    public function findRegion()
    {
        return $this->createQueryBuilder('r')->where('r.id < 16')->getQuery()->getResult();
    }

}
